// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shared.Contexts;

#nullable disable

namespace Shared.Migrations
{
    [DbContext(typeof(SmartAppDbContext))]
    partial class SmartAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("Shared.Models.Entities.SmartAppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConsumerGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventHubEndpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventHubName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IotHubConnectionString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
